### ISSUE TITLE
Problem demo

### ISSUE THREAD

**Issue by andresbelt** [AbdullahZN/kurento-room-node#1]
Listening at https://localhost:8443

browser error

Cannot GET /

any idea how to fix it

**Comment by AbdullahZN** [comment]
How did you run it ?

**Comment by andresbelt** [comment]
node main.js

**Comment by AbdullahZN** [comment]
Well yes sorry, I forgot to add usage description 😭 

**You should run** ``` npm run demo ```

It will install all the dependencies, and run a demo version.


I updated documentation accordingly, **don't forget to pull last changes** as it brings a lot of changes.
