### ISSUE TITLE
Error when trying run demo

### ISSUE THREAD

**Issue by MaksimDzhangirov** [AbdullahZN/kurento-room-node#2]
Hi! I am trying to run your code on Ubuntu 16.04, NodeJs version 8.9.3, npm version 5.5.1, but get error.

```    
const port = config.server.port;
                               ^

TypeError: Cannot read property 'server' of undefined
    at module.exports (/kurento-room-node/main/kurentoServer.js:6:25)
    at Object.<anonymous> (/kurento-room-node/static/build/dev-server.js:73:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Steps to reproduce in terminal:

1) git clone <your_repository>
2) npm run setup
3) npm run demo

**Comment by AbdullahZN** [comment]
Could not reproduce the issue with same config.
Is your `main/kurentoConfig.json` file correct ?

**Comment by MaksimDzhangirov** [comment]
my `main\kurentoConfig.json` file

```
{
  "kmsUri":"wss://<my server name>:8443/kurento",

  "secure" : {
      "key":"keys/server.key",
      "cert":"keys/server.crt"
    },

  "server": {
    "port": 8443,
    "uri": "https://localhost"
  }
}
```

In file `static\build\dev-server.js`, line 73 `kurentoServer` don't have second argument `config`. Is that correct?

**Comment by AbdullahZN** [comment]
It wasn't, I forced push correct version.
Please let me know if that works for you.

**Comment by MaksimDzhangirov** [comment]
There are 2 typos in your files.
In file `kurentoServer.js`, line 3 should be `const RoomManager = require('./roomManager');`, not `const RoomManager = require('./RoomManager');`
In file `roomManager.js`, line 2 should be `const Participant   = require('./participant');`, not `const Participant   = require('./Participant');`

After I corrected this typos, server successfully started. Thank you!

**Comment by AbdullahZN** [comment]
Oh yes totally, thank you very much.
I updated last commit :D
