### ISSUE TITLE
Help on error

### ISSUE THREAD

**Issue by fsp-rts-2** [AbdullahZN/kurento-room-node#3]
@AbdullahZN Hi, I'm now currently trying out this repo, but i got an error when trying to run the server. 

````
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '../keys/server.key'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at module.exports (/Users/ios/Desktop/testing/kurento-room-node/main/kurentoServer.js:9:17)
    at Object.<anonymous> (/Users/ios/Desktop/testing/kurento-room-node/main.js:10:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```` 

How do I fixed it?

**Comment by AbdullahZN** [comment]
How did you run it

**Comment by fsp-rts-2** [comment]
@AbdullahZN Sorry for the late reply. I run it by node main in the kurento-room-node. Actually how am I suppose to run it? 
May I ask, how do I implement this into the kurento ios demo?

**Comment by AbdullahZN** [comment]
you should `npm run dev` or `npm run demo`
if you just want to launch the server edit `main/kurentoConfig.json` with:
```json
"secure" : {
      "key":"./keys/server.key",
      "cert":"./keys/server.crt"
    },
``` 

what is it you want to do with **kurento-ios** ?

**Comment by fsp-rts-2** [comment]
@AbdullahZN ah I see. Sorry I'm new to all these. I'm trying to connect the kurento-ios to the room. But I am not sure how to do it. :(

Is it normal to get all these message?
![screen shot 2018-04-05 at 10 58 28 am](https://user-images.githubusercontent.com/37096007/38345152-112e911a-38c0-11e8-8744-ff48fbc321fd.png)

**Comment by fsp-rts-2** [comment]
@AbdullahZN Hi, just wondering, is this a working demo?? or do i have to implement some codes in order to make it work.

**Comment by chrismroberts** [comment]
@AbdullahZN thanks for putting this together.

I've successfully built the demo, and can add/remove participants. I added autoplay to the <video> elements so that they appear straight away.

However I'm having an issue where the video elements added when a participant joins just spin and never load. Image attached.

Any ideas?

Thanks

![image](https://user-images.githubusercontent.com/3083577/42563983-7be9fd7c-84f7-11e8-88d4-ade99e9977b1.png)

**Comment by AbdullahZN** [comment]
sorry for the late reply, 
If you have kurento-media-server installed yes it is.
the error you seeing is the kurento api that could not connect to the kurento-media-server 

I should update the doc with this.
The best way to do that will be:
- install docker 
- run `docker run -d --name kurento-media-server -p 8888:8888 kurento/kurento-media-server:xenial-latest`
- npm run dev
