### ISSUE TITLE
Remote video not loading

### ISSUE THREAD

**Issue by chrismroberts** [AbdullahZN/kurento-room-node#4]
@AbdullahZN thanks for putting this together.

I've successfully built the demo, and can add/remove participants. I added autoplay to the <video> elements so that they appear straight away.

However I'm having an issue where the video elements added when a participant joins just spin and never load. Image attached. I'm running Chrome, tried FireFox too.

Any ideas?

Thanks

![image](https://user-images.githubusercontent.com/3083577/42563983-7be9fd7c-84f7-11e8-88d4-ade99e9977b1.png)

**Comment by AbdullahZN** [comment]
Well that's really strange, I had to edit `static/src/kurentoRoom.js` in order to make it work.

You can see the diff here: https://github.com/AbdullahZN/kurento-room-node/compare/issue-4?expand=1

Is that working for you ?
