### ISSUE TITLE
[Deprecation] URL.createObjectURL with media streams is deprecated and will be removed

### ISSUE THREAD

**Issue by surinder-sammy** [AbdullahZN/kurento-room-node#5]
Hi,
I am getting this in console on Chrome.
[Deprecation] URL.createObjectURL with media streams is deprecated and will be removed in M68, around July 2018. Please use HTMLMediaElement.srcObject instead. See https://www.chromestatus.com/features/5618491470118912 for more details. at 
(anonymous) @ kurentoRoom.js?6f6d:101

Could you please help me to solve this.

**Comment by AbdullahZN** [comment]
Fixed with last commit should be fine now
