### ISSUE TITLE
GET https://localhost:8443/socket.io/?EIO=3&transport=polling&t=NF3jjyz net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by sraza295** [AbdullahZN/kurento-room-node#6]
After joining the room, showing this error.
please look at the screenshot.
![Screenshot from 2020-08-06 17-50-16](https://user-images.githubusercontent.com/37663062/89531293-9d182080-d80d-11ea-8e96-af8369f318a4.png)

**Comment by ninad-d** [comment]
@sraza295 right click on the link and open in new tab. It will show you message that its unsafe and do you want to proceed ahead. Click yes.
Reload the app and it should work.
The issue is due locally signed certificate.
